# Generated by Django 5.2.3 on 2025-06-27 08:25

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_author_profile_picture_alter_blog_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_picture',
            field=models.ImageField(default='authors/default.jpg', upload_to='authors/', validators=[core.models.validate_image_size, core.models.validate_image_type]),
        ),
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(default='blogs/default.jpg', upload_to='blogs/', validators=[core.models.validate_image_size, core.models.validate_image_type]),
        ),
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(default='categories/default.jpg', upload_to='categories/', validators=[core.models.validate_image_size, core.models.validate_image_type]),
        ),
    ]
