# Generated by Django 5.2.3 on 2025-06-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thumbnail_caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
