# Generated by Django 5.2.3 on 2025-07-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_blog_thumbnail_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='excerpt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
