# Generated by Django 5.2.3 on 2025-07-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_category_excerpt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='excerpt',
        ),
        migrations.AddField(
            model_name='blog',
            name='excerpt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
