# Generated by Django 5.2.3 on 2025-07-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_category_excerpt_blog_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='excerpt',
            field=models.CharField(default='No excerpt provided.', max_length=160),
            preserve_default=False,
        ),
    ]
