# Generated by Django 5.2.3 on 2025-07-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_blog_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default='No description'),
            preserve_default=False,
        ),
    ]
