# Generated by Django 5.2.3 on 2025-07-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('editor', 'Editor')], default='editor', max_length=20),
        ),
    ]
