# Generated by Django 5.2.3 on 2025-07-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_author_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='excerpt',
            field=models.CharField(max_length=200),
        ),
    ]
